language: php
env:
  global:
    - TM_TRAVIS=1
    - TM_TEST_ACCOUNTCODE=qa
    - TM_TEST_SERVER=https://qa.ticketmatic.com
    - TM_TEST_ACCESSKEY=842dda885ec6024f934a40c0
install:
  - composer install
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
